### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by GJRTimmer** [bucardo/check_postgres#117]
Could you please add a LICENSE file to the repository.

I'm trying to add this project as installable package to Alpine Linux, and I would like either a LICENSE file or confirmation that it is indeed a BSD license.

Thanks in advance.

**Comment by pnorman** [comment]
The license is stated at https://github.com/bucardo/check_postgres#license-information

**Comment by GJRTimmer** [comment]
Yeah, I understand, but please add a LICENSE file to this repository. Required for automatic build process of Linux Alpine build packages. The license file needs to be stored within the package to be placed on the target machine.

**Comment by petere** [comment]
There is also a license inside `check_postgres.pl`.

**Comment by GJRTimmer** [comment]
Yes I understand. But it is common pracrice to have a LICENSE file in your repository which can be shipped with a software product when packaging for a linux distribution. It will take 2 sec to make it because with github you can simply select the license you want to add.

I kinda get the idea from the comments that no one wants to add this default file to the repository. Because everyone is referering to look elsewhere.

Why don't you want to add this default file ?

**Comment by GJRTimmer** [comment]
Without the LICENSE file this repository does not comply to default conventions and the package has to be removed from the repository. And I really like this piece of software.

Please reconsider to adding this like all the other repo's on github, I really don't want to remove the package from alpine.

**Comment by ChristophBerg** [comment]
Re: Gert-Jan Timmer 2017-04-09 <bucardo/check_postgres/issues/117/292766037@github.com>
> Without the LICENSE file this repository does not comply to default conventions and the package has to be removed from the repository. And I really like this piece of software.
> 
> Please reconsider to adding this like all the other repo's on github, I really don't want to remove the package from alpine.

How come Alpine is much stricter there than say Debian?

Maybe you could create a pull request for this?

Christoph

**Comment by GJRTimmer** [comment]
Don't know. I've added check_postgres. And this is one of the open issues
before it can be moved from the testing repo to the main.

I think it might have to do with the fact that alpine has become the
defacto standard for Docker containers. Which means the license has to be
within the package and not as reference.

But that's just a quess.

Op ma 10 apr. 2017 10:19 schreef Christoph Berg <notifications@github.com>:

**Comment by machack666** [comment]
Created explicit LICENSE file; it **is** just standard 2-clause BSD.  Also don't see any issues whatsoever about having it explicit in a separate file.

HTH

**Comment by GJRTimmer** [comment]
Thank you. @David now the package manager for alpine can place it on disk.

Thank you very much.

Op ma 10 apr. 2017 17:08 schreef David Christensen <notifications@github.com
>:

Closed #117 <https://github.com/bucardo/check_postgres/issues/117>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bucardo/check_postgres/issues/117#event-1036646435>,
or mute
the thread
