### ISSUE TITLE
txn_idle requires superuser to view key pg_stat_activity fields

### ISSUE THREAD

**Issue by dtseiler** [bucardo/check_postgres#120]
When querying the pg_stat_activity field as a non-superuser (ie my monitoring user), the query field only returns "`<insufficient privilege>`" for all rows.

This results in this message returned from the check:

> `POSTGRES_TXN_IDLE UNKNOWN: DB "postgres" (host:xxx) No matches - please run as a superuser | time=0.01s`

Curious why we really need to even query that field. Can't we just look at the state and the state change time?

EDIT: Actually looks like non-superuser can't view state, state_change, query_start or xact_start either. They all return null unless you are superuser.

**Comment by dtseiler** [comment]
Example:

```
# select pid, query, state, xact_start, query_start, state_change from pg_stat_activity where pid=3942;
-[ RECORD 1 ]+------------------------------
pid          | 3942
query        | ROLLBACK
state        | idle
xact_start   | [null]
query_start  | 2017-09-07 11:05:41.490508-05
state_change | 2017-09-07 11:05:41.490589-05

Time: 0.661 ms
# set session authorization monitor;
SET
Time: 0.238 ms
> select pid, query, state, xact_start, query_start, state_change from pg_stat_activity where pid=3942;
-[ RECORD 1 ]+-------------------------
pid          | 3942
query        | <insufficient privilege>
state        | [null]
xact_start   | [null]
query_start  | [null]
state_change | [null]
```

**Comment by machack666** [comment]
Hi @dtseiler regarding your later edit, that's exactly the issue.

**Comment by dtseiler** [comment]
So my reason for posting this is that there is no note in the man page for txn_idle to say that it requires superuser. At the very least that should be added. Alternatively, I'd love to know if there's a set of grants we can apply to a non-superuser to do this. I'd very much not want to have my monitor user have superuser privs.

**Comment by machack666** [comment]
@dtseiler good point about the note; in Pg 10 you can GRANT `pg_read_all_stats`.  I'll add notes to that effect.

**Comment by machack666** [comment]
Clarified in f946cff.  It looks like there had been some mention of the superuser there already, but it's definitely good to mention the newer workaround.
