### ISSUE TITLE
Syntax errors in 2.23.0 with older Perl versions

### ISSUE THREAD

**Issue by esabol** [bucardo/check_postgres#126]
I just upgraded to version 2.23.0 and am getting the following errors:
```
Global symbol "$st" requires explicit package name at /path/to/check_postgres.pl line 8104.
Global symbol "$st" requires explicit package name at /path/to/check_postgres.pl line 8114.
Global symbol "$st" requires explicit package name at /path/to/check_postgres.pl line 8126.
```

**Comment by esabol** [comment]
This appears to only be a problem with older versions of Perl, like 5.8.8.
5.16.3 is OK with it.

**Comment by esabol** [comment]
Here's a quick patch:
```
--- check_postgres-2.23.0/check_postgres.pl     2017-10-31 09:26:28.000000000 -0400
+++ ../check_postgres.pl        2017-11-03 18:56:23.130876000 -0400
@@ -8101,8 +8101,8 @@
         next if skip_item($r->{datname});
 
         ## We do a lot of filtering based on the current_query or state in 9.2+
-        my $cq = $r->{query} // $r->{current_query};
-        my $st = $r->{state} // '';
+        my $cq = defined($r->{query}) ? $r->{query} : $r->{current_query};
+        my $st = defined($r->{state}) ? $r->{state} : '';
 
         ## Return unknown if we cannot see because we are a non-superuser
         if ($cq =~ /insufficient/) {
```

**Comment by ChristophBerg** [comment]
Hi,
which OS is that where Perl was still at 5.8?

**Comment by esabol** [comment]
RHEL 5.something

**Comment by ChristophBerg** [comment]
@esabol: imho it makes a difference if that Perl 5.8-OS is still supported, or if we should rather move on and use more modern Perl features. In this case, it's easy enough, and I'm also updating the travis testsuite to use 5.8 rather than 5.10 so we'll know should we break it again.
Thanks!

**Comment by esabol** [comment]
Well, the code, META.yml, and Makefile.PL all seem to indicate 5.6.1 is the minimum required Perl version:
https://github.com/bucardo/check_postgres/blob/e3409de9916ccd596081a8074e34792b4ad7b5f2/check_postgres.pl#L18

But thank you for making those changes and for all your work with this project. Cheers!
