### ISSUE TITLE
Postgres10 wrong version shown with --connection

### ISSUE THREAD

**Issue by r4tt4** [bucardo/check_postgres#137]
at the moment the login check shows the wrong version for a Postgres 10:

./check_postgres.pl --action=connection --host=10.90.20.40 --dbname=postgres --dbuser=xxx --dbpass=xxx
POSTGRES_CONNECTION OK: DB "postgres" (host:10.90.20.40) version **4.8.5** | time=0.07s

using --version it works:
/tmp/check_postgres.pl --action=version --host=10.90.20.40 --dbname=postgres --dbuser=xxx --dbpass=xxx --warning=10 --critical=10
POSTGRES_VERSION OK: DB "postgres" (host:10.90.20.40) version **10.1** | time=0.07s

no problems on older 9.x version.

would be great if you could fix that issue, too.

**Comment by r4tt4** [comment]
Just fixed that problem myself:

under check_connection

replace this:
my $ver = ($db->{slurp}[0]{v} =~ /(\d+\.\d+\S+)/) ? $1 : '';

with that:
my $ver = ($db->{slurp}[0]{v} =~ /((\d+\.?\d+)(\w+|\.\d+))/) ? $1 : '';

done.

**Comment by machack666** [comment]
Hi @r4tt4, thanks for the report.  I've fixed it up a little differently, but that was definitely a spot where we'd missed the change to 2-digit version numbers, thanks.

Fixed in d720417.
