### ISSUE TITLE
when installing, make test raise many error, such as "make: *** [test_dynamic] Error 255"

### ISSUE THREAD

**Issue by tuhaolam** [bucardo/check_postgres#140]
t/02_bloat.t ............... Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: t . /home/tgc/monitor/check_postgres/blib/lib /home/tgc/monitor/check_postgres/blib/arch /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl) at t/CP_Testing.pm line 10.
BEGIN failed--compilation aborted at t/CP_Testing.pm line 10.
Compilation failed in require at t/02_bloat.t line 11.
BEGIN failed--compilation aborted at t/02_bloat.t line 11.
# Looks like your test exited with 2 before it could output anything.
t/02_bloat.t ............... Dubious, test returned 2 (wstat 512, 0x200)
Failed 30/30 subtests 
---------------------------
t/02_version.t ............. Can't exec "initdb": No such file or directory at t/CP_Testing.pm line 96.
Use of uninitialized value in pattern match (m//) at t/CP_Testing.pm line 96.
Could not determine the version of initdb in use!
# Looks like your test exited with 2 before it could output anything.
---------------------------
  Parse errors: Bad plan.  You planned 12 tests but ran 0.
t/04_timeout.t           (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 2 tests but ran 0.
Files=55, Tests=151,  2 wallclock secs ( 0.08 usr  0.06 sys +  1.82 cusr  0.10 csys =  2.06 CPU)
Result: FAIL
Failed 44/55 test programs. 0/151 subtests failed.
Makefile:783: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255

**Comment by ChristophBerg** [comment]
The testsuite needs the "DBI" and "DBD::Pg" perl modules.
Furthermore, if "initdb" is not in $PATH, do "make test PGBINDIR=/usr/lib/postgresql/10/bin".
