### ISSUE TITLE
Use pg_ls_waldir() in PG10 instead of pg_ls_dir()

### ISSUE THREAD

**Issue by keithf4** [bucardo/check_postgres#145]
I see there are already conditionals in the code to allow the `wal_files` check to work in PG10 after the folder name change. What would be better would be to use the `pg_ls_waldir()` function instead. This would allow any role granted `pg_monitor` to be able to run this check. `pg_ls_dir()` always requires a superuser to use it.

**Comment by machack666** [comment]
Hi @keithf4,

Definitely don't disagree with you on that being a better approach, however the way we currently handle different different logic depending on the database almost exclusively involves adjusting the query for the db version in question; from my read, this would involve quite a bit more extensive work than just changing the function in question.  If you have some ideas on how to rework this without having to put in separate code paths per database version I'd love to review them and/or submit a PR.

Best,

David

**Comment by keithf4** [comment]
If you mean ensuring that the role in question has the `pg_monitor` system role granted, I don't think that's anything check_postgres needs to worry about. It should be as simple as running one query or the other depending on the version detected. I don't see any further complexity than that.

**Comment by ChristophBerg** [comment]
The actual code change is pretty trivial, I just pushed a PR.
What's less trivial is adjusting the hackery around $cp->create_fake_pg_table() which expects matching datatypes on function call and return, but pg_ls_waldir() takes nothing and returns some columns. The workaround is okayish, but doesn't use a function from CP_Testing.pm. Boo.

**Comment by keithf4** [comment]
Thank you!
