### ISSUE TITLE
https://bucardo.org/check_postgres/latest_version.txt regression from 2.24.0 to 2.23.0

### ISSUE THREAD

**Issue by esabol** [bucardo/check_postgres#151]
2.24.0 is the latest version, but https://bucardo.org/check_postgres/latest_version.txt now (as of sometime today, 2018-11-05) says 2.23.0. Prior to today, that URL correctly reported 2.24.0. I presume the change is unintentional?

The https://bucardo.org/check_postgres/ web page appears to have regressed to version 2.23, also.

**Comment by ulyszk** [comment]
I have same issue. Thank you in advance for frixing this.

**Comment by KAMI911** [comment]
I got this issue too.

**Comment by machack666** [comment]
Thanks, this was indeed an accident when releasing the latest Bucardo.  Updated again!
