### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by guruguruguru** [bucardo/check_postgres#159]
Hey,

do you know when there will be a new release? We are waiting for https://github.com/bucardo/check_postgres/commit/fd9702c9321a7e68965fa07e75d4f38e4de88d9c in an official release.
This issue is fixed since September 2018.

Thanks a lot,
Dennis

**Comment by justinpryzby** [comment]
+1 for releasing fix for fd97

**Comment by justinpryzby** [comment]
+1 for releasing with fix for fd97

**Comment by mbanck** [comment]
+1 from me as well

**Comment by mbanck** [comment]
@turnstep or maybe at least a 2.24.1 point release with fd9702c ?

**Comment by turnstep** [comment]
Will get something out soon

**Comment by turnstep** [comment]
Version 2.25.0 has been released

**Comment by devrimgunduz** [comment]
@turnstep where is the release? Cannot find on https://github.com/bucardo/check_postgres/releases or bucardo website.

**Comment by turnstep** [comment]
Sorry, see if it is appearing for you now.

**Comment by devrimgunduz** [comment]
Thanks @turnstep !

**Comment by esabol** [comment]
Close this issue, please.
