### ISSUE TITLE
checking database size: ERROR: permission denied for database xyz

### ISSUE THREAD

**Issue by esabol** [bucardo/check_postgres#161]
Back in March 2018, I revoked some public schema permissions as recommended by

https://wiki.postgresql.org/wiki/A_Guide_to_CVE-2018-1058:_Protect_Your_Search_Path

I just created a new database (let's call it "xyz") for the first time since then, and I'm getting "ERROR: permission denied for database xyz" when I execute:
```
check_postgres -H someserver --dbuser=someuser --action=database_size -w 100 -c 200
```
I tried adding "--exclude=xyz" to the arguments, hoping to exclude the "xyz" database, but it had no effect.

Any idea what permissions I need to grant here to get the database_size check to work?

**Comment by esabol** [comment]
Oh, I should have also mentioned that I'm using PostgreSQL 10.8.

**Comment by machack666** [comment]
Looks like it's likely an un-granted `CONNECT` priv for the new database.  I assume you changed the default GRANTs as part of the hardening process.

**Comment by esabol** [comment]
Yeah, that was it. Thanks!
```SQL
   grant connect on database xyz to someuser;
```
fixed it. Sorry, that probably should have been obvious, but I think I was remembering how connect permissions used to be granted by default.
