### ISSUE TITLE
Slave reporting master server clock is ahead

### ISSUE THREAD

**Issue by lpossamai** [bucardo/check_postgres#164]
Hi. When executing the check_postgres script I get the following message:

`POSTGRES_HOT_STANDBY_DELAY UNKNOWN: DB "dbtest1" (host:192.168.99.14) Slave reporting master server clock is ahead, check time sync | time=0.21s`

I've checked the date and time on both servers and it seems to be fine. The command I'm using is:
`/usr/lib/nagios/plugins/check_postgres_hot_standby_delay --host 192.168.99.11,192.168.99.14 --dbname dbtest1 --dbuser monitoring --dbpass dbpassword --critical '16777216 and 10 min' --warning '1048576 and 2 min'`

What could it be? I'm using postgres 10.

**Comment by pinakesh** [comment]
Hi,

I am also getting the same error, please can someone help me understand what causes this error and how to resolve it?

**Comment by ubellavance** [comment]
It looks like the time reported by the operating system on the primary is significantly different from the time on the replica. For example, it could be 11:03:43 on the replica and 11:05:54 on the primary.
 Do you use NTP to make sure your clocks are in sync with time servers?

**Comment by lpossamai** [comment]
I've fixed this issue ages ago and can't remember what I did, unfortunately. I'll close this issue now.
