### ISSUE TITLE
initdb

### ISSUE THREAD

**Issue by defadmin** [bucardo/check_postgres#168]
I don't have initdb on my monitoring server, why do I need this to pass the install?  isn't this to check remote servers?

**Comment by df7cb** [comment]
initdb is only necessary for running the testsuite.

**Comment by defadmin** [comment]
Can I install it without running the testsuite?  I might be the only one :)  but I was following the instructions in the README.md, and when it failed the testsuite I figured it wouldn't go on.  But I ran make install and it seems to have installed.  Thanks
    perl Makefile.PL
    make
    env -i make test
    make install
