### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by leegarrett** [bucardo/check_postgres#188]
I noticed that a few bugs I ran into in 2.23 have been fixed in the tip of master. Since the last release has been nearly two years ago, can we have a new 2.24 release?

**Comment by bmomjian** [comment]
Is there a reason you are not running 2.25.0 instead?

**Comment by leegarrett** [comment]
Eh, off by two. I meant 2.26.0.

**Comment by turnstep** [comment]
Just released 2.26.0
