### ISSUE TITLE
Is this Project still being maintained?

### ISSUE THREAD

**Issue by MichaelDBA** [bucardo/check_postgres#195]
I don't see any updates in quite a while and a bunch of open issues are not being addressed.  So the obvious question in the title.

**Comment by turnstep** [comment]
Yep - working through the backlog now! If you have particular issues or PRs you want to prioritize, please let me know.

**Comment by esabol** [comment]
@turnstep Thanks for the release! Please [tag the 2.26.0 release here on GitHub](https://github.com/bucardo/check_postgres/releases) when you have time. 😄
