### ISSUE TITLE
hot_standby_delay doesn't work at all or poorly documented

### ISSUE THREAD

**Issue by phinjensen** [bucardo/check_postgres#35]
ID: 95
Version: unspecified
Date: 2011-12-22 09:54 EST
Author: Peter Eisentraut (peter_e@gmx.net)

---

check_postgres version 2.18.0

I cannot get hot_standby_delay to work at all.  Something like this ought to do
something:
```
$ check_postgres_hot_standby_delay --dbhost=localhost --dbhost2=localhost
--dbport=5435 --dbport=5435 --dbuser=postgres -w 30 -c 100
Use of uninitialized value $slave in numeric eq (==) at
/usr/bin/check_postgres_hot_standby_delay line 4581.
POSTGRES_HOT_STANDBY_DELAY UNKNOWN: DB "postgres" (host:localhost) (port=5435)
Invalid query returned: receive <PIPE> \n replay  <PIPE> \n  | time=0.09s
```
An actual example in the documentation would be nice, in case this is not a
real bug but just a misunderstanding.

**Comment by ChristophBerg** [comment]
This was fixed earlier as part of 6b765c839eaf80499f68d412a897f61f11db9bfc.
