### ISSUE TITLE
Warning: the following files are missing in your kit: MYMETA.yml

### ISSUE THREAD

**Issue by chrber** [bucardo/check_postgres#52]
[.... check_postgres]# perl Makefile.PL
Configuring check_postgres 2.21.0
Checking if your kit is complete...
Warning: the following files are missing in your kit:
	MYMETA.yml
Please inform the author.
Writing Makefile for check_postgres

Please inform the author. Which I have done by opening this issue

Thanks.

**Comment by ChristophBerg** [comment]
Our release tarballs do contain MYMETA.yml, the warning is only visible from git checkouts. I don't think this is an issue.
