### ISSUE TITLE
2.21.0 Documentation bug

### ISSUE THREAD

**Issue by chrber** [bucardo/check_postgres#53]
OS: SL 2.6.32-358.18.1.el6.x86_64

plugins]# ./check_postgres.pl --action=connection --db=chimera -H localhost -p 5432 -u postgres
Cannot find Time::HiRes, needed if 'showtime' is true at ./check_postgres.pl line 1267.

This was solved by installing:

yum install perl-Time-HiRes.x86_64

**Comment by ChristophBerg** [comment]
Hi,

this is actually documented, and the error message you are seeing is already the nice one because check_postgres catches this case.

```
DEPENDENCIES
       Time::HiRes (if $opt{showtime} is set to true, which is the default)
```
