### ISSUE TITLE
txn_idle check requires unnecessary superuser privileges in PG 9.2+

### ISSUE THREAD

**Issue by coverprice** [bucardo/check_postgres#81]
The following check is made when filtering rows from the txn_idle check.
Line 7611 (version 2.21.0)

        if ($cq =~ /insufficient/o) {
            add_unknown msg('psa-nosuper');
            return;
        }

This check on the "current_query" column is unnecessary for PG 9.2+ because the "idle in transaction" information was moved to the new "state" column and this requires no special privileges to view. The above check prevents running the PG9.2+ Nagios txn_idle checks with a non-superuser account.

I believe the fix is simply to add a version check in the `if` statement above, something like (pseudo-code):

    if($pg_version < 9.2  and $cq =~/insufficient/o) {

**Comment by ipeacocks** [comment]
Seems that project is already unsupported.

I`ve tried to add as you adviced:

````
# at the beggining
our $pg_version = 9.4;
````
````
at 7611 line:

        if($pg_version < 9.2  and $cq =~/insufficient/o) {
            add_unknown msg('psa-nosuper');
            return;
        }
````

Thank you.

**Comment by ChristophBerg** [comment]
Hi,

it's unfortunately not true that the "state" column is visible for all users. A possible workaround if only transactions of a specific user are to be checked is to connect as this user, and to supply --includeuser=<thisuser>. I'll document that.
