### ISSUE TITLE
check_txn_idle filter column

### ISSUE THREAD

**Issue by sebastianwebber** [bucardo/check_postgres#87]
Hi There,

We are having some issues with the check_txn_idle function.

Reviewing the code, we found the running query that causes the problem by  using the 'query_start' column in a place of 'state_change' column.

More details at: http://www.postgresql.org/docs/9.2/static/monitoring-stats.html#PG-STAT-ACTIVITY-VIEW

**Comment by ChristophBerg** [comment]
Closed via c09e7840ed82db6274116ce9b83fbdbc72f940c8.
