### ISSUE TITLE
[xpost mailing list] query_time returning long queries that don't exist?

### ISSUE THREAD

**Issue by apuschak** [bucardo/check_postgres#89]
Hi,

Occasionally I get these Nagios alerts:

PG QUERY TIME;OK;HARD;2;POSTGRES_QUERY_TIME OK: DB "postgres" longest
query: 0s
PG QUERY TIME;CRITICAL;HARD;2;POSTGRES_QUERY_TIME CRITICAL: DB
"postgres" longest query: 117s PID:8775
PG QUERY TIME;CRITICAL;SOFT;1;POSTGRES_QUERY_TIME CRITICAL: DB
"postgres" longest query: 57s PID:8775

They are running this command on the database server itself:

check_postgres.pl --action=query_time --warning=25 --critical=30

The database is logging every query, but I don't have any queries at
that time that match these times or even close to it.

I yum installed check_postgres:

Installed Packages
Name : check_postgres
Arch : noarch
Version : 2.19.0
Release : 1.el6
Size : 533 k
Repo : installed
From repo : epel
Summary : PostgreSQL monitoring script
URL : http://bucardo.org/wiki/Check_postgres
License : BSD

and running postgres 8.4:

Installed Packages
Name : postgresql
Arch : x86_64
Version : 8.4.13
Release : 1.el6_3
Size : 14 M
Repo : installed
From repo : updates
Summary : PostgreSQL client programs
URL : http://www.postgresql.org/
License : PostgreSQL

What could be causing these?

Thanks for your help,
Andrew

**Comment by ChristophBerg** [comment]
I believe this should be fixed via #88.
