### ISSUE TITLE
No errors displayed upon command execution

### ISSUE THREAD

**Issue by nidhhoggr** [bucardo/check_postgres#97]
When I execute the following I get no errors:

./check_postgres --host=startup-production-database
<code>
[root@nagios libexec]# ./check_postgres --host=startup-production-database

Usage: check_postgres <options>
 Try "check_postgres --help" for a complete list of options
 Try "check_postgres --man" for the full manual
</code>

Extra params provide the same result:

<code>
[root@nagios libexec]# ./check_postgres --host=startup-production-database --port=5432 --dbuser=pg_produser --dbpass=password --dbname=advertising_api

Usage: check_postgres <options>
 Try "check_postgres --help" for a complete list of options
 Try "check_postgres --man" for the full manual
</code>

Am I supposed to install a dependency or is there something I am missing?

**Comment by ChristophBerg** [comment]
You need to chose which action should be executed, either using ./check_postgres --action=foo or by invoking a ./check_postgres_foo symlink.
