### ISSUE TITLE
POSTGRES_LAST_ANALYZE pg_catalog.pg_type

### ISSUE THREAD

**Issue by guettli** [bucardo/check_postgres#98]
We get errors since the table `pg_catalog.pg_type` (and many more) were not analyzed and vacuumed during the last days.

check_postgres only complains about tables which hardly change.

Maybe it is related to this question:

http://stackoverflow.com/questions/22796124/auto-analyze-not-running-for-all-tables-in-postgres-9-2-database

> It does look like the tables should be vacuum analyzed when 10% of of the tuples are changed.
> Based on the posed postgresql.conf setting.

I could create a list of all tables to ignore by hand, but that's ... manual work I would like to avoid.

Is there a way to improve check_postgres? If you give me some hints, I could try to create a pull request.

**Comment by ChristophBerg** [comment]
This is more a general PostgreSQL "problem" than a check_postgres one. Tables that do not change need no vacuum or analyze. This makes the last_analyze and last_vacuum actions unsuitable to be applied to all tables unconditionally. Better make a whitelist and check tables only that are problematic in the database in question.

**Comment by guettli** [comment]
I am happy with your decision to close this.

Still one remark: Could check_postgres query the "last modified" flag of a table (if such a flag exists)?
I like to avoid to care for whitelists.

**Comment by ChristophBerg** [comment]
Re: Thomas Güttler 2016-06-09 <bucardo/check_postgres/issues/98/224850223@github.com>
> I am happy with your decision to close this.
> 
> Still one remark: Could check_postgres query the "last modified" flag of a table (if such a flag exists)?
> I like to avoid to care for whitelists.

Such a flag does not exist, making this problem rather hard to solve
without deeper insight into the schema/application in use.

Christoph

**Comment by guettli** [comment]
@ChristophBerg OK, now it is clear. If there is no such flag, you can't calculate the age. Let's leave this closed.
